### ISSUE TITLE
Broken Link in README for Craft Query Paremeters

### ISSUE THREAD

**Issue by kragit** [nmaier95/craft-shopify-product-fetcher#114]
In the [Query Parameters](https://github.com/craftcms/shopify?tab=readme-ov-file#query-parameters) section of the README, the following text is present:

> The following element query parameters are supported, in addition to [Craft’s standard set](https://craftcms.com/docs/5.x/element-queries.html).

The link is broken and should likely link to:

`https://craftcms.com/docs/5.x/development/element-queries.html`

**Comment by nfourtythree** [comment]
Thanks for reporting!
