### ISSUE TITLE
getDefaultVariant() returning null in a EVENT_BEFORE_SYNCHRONIZE_PRODUCT event during the sync

### ISSUE THREAD

**Issue by bleepsandblops** [nmaier95/craft-shopify-product-fetcher#117]
### Description
It looks like some products do not have a default variant, as I'm getting this error message when running the sync with an event (see below):
```
Exception 'TypeError' with message 'craft\shopify\elements\Product::getDefaultVariant(): Return value must be of type array, null returned'

in /var/www/html/vendor/craftcms/shopify/src/elements/Product.php:320
```

My code of the event:
```
Event::on(
            Products::class,
            Products::EVENT_BEFORE_SYNCHRONIZE_PRODUCT,
            function(ShopifyProductSyncEvent $event) {
                // Example 1: Cancel the sync if a flag is set via a Shopify metafield:
                $metafields = $event->element->getMetaFields();
                $product = $event->element;

                if (
                    ($product->shopifyStatus == 'archived') ||
                    ($product->publishedAt == null)
                ) {
                    $event->isValid = false;
                }

                // Example 2: Set a field value from metafield data:
                if (($event->isValid) && ($product->getDefaultVariant() !== null)) {
                    echo $product->title . "\n";
                    echo $product->publishedScope . "\n";
                    $event->element->setFieldValue('shopifyPrice', $product->getDefaultVariant()['price']);
                }
            }
        );
```

The only way to make it work is to remove the return type in the `getDefaultVariant()` function definition [here](https://github.com/craftcms/shopify/blob/05ef415fbe26b1b3c37171a5956c9d857abced73/src/elements/Product.php#L318).

It's a shop with thousands of products, but I can't quite find the reason why some go through and some don't.

### Steps to reproduce

1. Run the `./craft shopify/sync/products` command
2. Get the error message on some products

### Additional info

- Craft version: 4.9.5
- PHP version: 8.2.3
- Database driver & version: MariaDB 10.3.38
- Plugins & versions: Shopify 4.1.2

**Comment by bleepsandblops** [comment]
Apologies, this looks like a duplicate of https://github.com/craftcms/shopify/issues/112

**Comment by nfourtythree** [comment]
Information updated in #112 .

Closing this as a duplicate.

Thanks!
