### ISSUE TITLE
Webhooks tab not appearing

### ISSUE THREAD

**Issue by FirePower-Capital** [nmaier95/craft-shopify-product-fetcher#123]
### Description
I've followed the setup instructions (twice) in multiple environments. Saving the all the settings under API Connection doesn't reveal a Webhooks tab. No errors are showing. All values have been double checked; webhook event version in Shopify is `2023-10`. Not seeing any Shopify-related errors in logs either.

### Steps to reproduce

1. Follow 4.x installation instructions and input ENV variables 
2. Save

### Additional info

- Craft version: Craft Solo 4.12.3
- PHP version: 8.2.20
- Database driver & version: MySQL 8.0.35
- Plugins & versions: Shopify 4.1.2

**Comment by nfourtythree** [comment]
Hi @FirePower-Capital 

Thank you for your feedback! I attempted to replicate the issue you reported, but I was unable to do so.

I’ve included a video demonstrating how to add the Shopify credentials in the settings. This process should allow the webhooks link to appear in the control panel navigation.

Could you please confirm if you followed the same steps? 

Thanks!

**Comment by nfourtythree** [comment]
Apologies it appears the video didn't attach, here it is:


https://github.com/user-attachments/assets/da18c9ec-02bd-458d-baf4-5c75d13061a1

**Comment by FirePower-Capital** [comment]
Hi [nfourtythree](https://github.com/nfourtythree), thanks for the quick reply. I'm using Craft 4, but yes, I've followed those exact steps. Let me know what other info you need here

**Comment by nfourtythree** [comment]
Hi @FirePower-Capital 

Thank you for your response and confirming which versions you were using.

I have just tried this process on Craft `4.x` and the compatible version of this plugin and everything seemed to work as expected.


https://github.com/user-attachments/assets/6f694332-09cd-4e49-9331-ffb8af46640a

[We conditionally show the webhooks navigation item](https://github.com/craftcms/shopify/blob/4.x/src/Plugin.php#L295-L302) based on the fact we can create a session with the Shopify API. This leads me to believe that something is breaking down at this point and it is likely to do with the credentials.

Can you double-check the details you are providing in the settings for the Shopify plugin? Then if you believe those to be correct I would suggest Xdebugging the API session in the section of the code I linked above to see why this might be failing.

Thanks!

**Comment by FirePower-Capital** [comment]
Figured it out. There's a conflict with [Control Panel Nav plugin](https://github.com/verbb/cp-nav). The Webhook tab doesn't even appear in its Settings. The only way around it is to disable the plugin.

**Comment by nfourtythree** [comment]
Hi @FirePower-Capital 

Thank you for the info.

Sounds like an issue similar to this one in which a solution is provided: https://github.com/verbb/cp-nav/issues/120#issuecomment-1396823468

Closing this issue now it is identified as an issue regarding another plugin.

Thanks!
