### ISSUE TITLE
Shopify plugin does not work

### ISSUE THREAD

**Issue by brandonkelly** [nmaier95/craft-shopify-product-fetcher#128]
Hey all,

Quick question, new to integrating Shopify into Craft CMS (v5.5.x). I've setup a custom app within Shopify and used the provided credentials to access the shop like so:

```
# Shopify
SHOPIFY_API_KEY="***********2e5c"
SHOPIFY_API_KEY_SECRET="***********db30"
SHOPIFY_ACCESS_TOKEN="***********8ac3"
SHOPIFY_HOST_NAME="**********.myshopify.com"
```

However, when I click webhooks in the navigation pane I get the following errror:

```
Shopify\Exception\RestResourceRequestException
REST request failed: "[API] Invalid API key or access token (unrecognized login or wrong password)"
```

I read on the Spotify Plugin page from Pixel & Tonic that I need to select a specific Webhook event version, however, this version is no longen available.

What am I missing here?

Cheers,
Allard

_Originally posted by @dolphiq-allard in https://github.com/craftcms/cms/discussions/16311_

**Comment by nfourtythree** [comment]
Hi @dolphiq-allard

Thank you for reporting this. We have just pushed version 5.3.0 of the Shopify plugin which now supports version `2024-10` of the Shopify API.

You should be able to create your app in Shopify and connect it to the plugin as described in the README.

Thanks!
