### ISSUE TITLE
JS is broken for generated matrix fields.

### ISSUE THREAD

**Issue by ryanpcmcquen** [nmaier95/craft-shopify-product-fetcher#15]
When refactoring the JS, you did not account for the scenario where the field is generated after the page loads (as Matrix fields can be).

![craft_shopify_product_fetcher_broken_js](https://user-images.githubusercontent.com/772937/77367032-85d10e80-6d16-11ea-8e38-66c3677fd6b6.gif)

**Comment by ryanpcmcquen** [comment]
I called this out in the PR: https://github.com/nmaier95/craft-shopify-product-fetcher/pull/9#discussion_r393218690

**Comment by nmaier95** [comment]
To be hones im by far not a craft pro and I did not quite understand the meaning of your comment in PR #9. My apologies. I'll be working on a fix.

**Comment by ryanpcmcquen** [comment]
@nmaier95, also make sure to accommodate multiple versions of the field on the same page.

**Comment by ryanpcmcquen** [comment]
@nmaier95, reverting c2afe10fa558ce09e1d27fc4eeab8a94c10cd268 is my temporary workaround, although I am missing out on the nice CSS you added.
