### ISSUE TITLE
Collections Documentation

### ISSUE THREAD

**Issue by bfjare** [nmaier95/craft-shopify-product-fetcher#19]
Looks like Collections only pulls the collection id.  Is it possible to give some basic documentation on the best way to pull a list of collections?

Thanks in advance.

**Comment by nmaier95** [comment]
@TonyDeStefano or @ryanpcmcquen may you help answering here?

**Comment by TonyDeStefano** [comment]
@bfjare if you are wanting to pull a list of products by collection, you need to use this Shopify endpoint in your code: /2020-01/products.json?limit=200&collection_id=[collection id]

**Comment by bfjare** [comment]
Sorry, I guess I'm not fully understanding how this integrates with twig.

**Comment by nmaier95** [comment]
I think we actually didn't expose the collection-service-calls to the shopify-twig-variable, did we @TonyDeStefano ? If thats what @bfjare needs...?

**Comment by bfjare** [comment]
@nmaier95 I'm just hoping to be able to use it to select collections in the fields to build navigation and then create product listing pages for those collections. The documentation isn't very clear how this works in twig is all.  Right now I have some of what I need to be done by creating a simple plugin with variables going directly through the API but it's less than elegant.

Actually would be happy to sponsor some expansion to the plugin.  I don't think it needs very much and makes it a better tool for us moving forward.

**Comment by ryanpcmcquen** [comment]
@bfjare, is there a reason you can't just add a field with the type of 'Shopify Collection'?
<img width="327" alt="Screen Shot 2020-04-22 at 9 26 14 AM" src="https://user-images.githubusercontent.com/772937/80007621-5b8c8100-847b-11ea-8ead-68c0206cedd9.png">

**Comment by bfjare** [comment]
@ryanpcmcquen  That's what I am using but all it produces is the collection ID number.  I cant grab handles, title, etc, or if I can I'm not understanding how it works in Twig other then "use this endpoint". I'm well aware of the fact this is a me problem.

**Comment by ryanpcmcquen** [comment]
@bfjare, that's all it returns and stores. You will want your front end to fetch from any other data from Shopify directly using their API. The advantage here is storing less data inside of Craft itself, and it also eliminates the issue of data 'freshness' you would have if you chose to also store all data inside of Craft.

**Comment by bfjare** [comment]
@ryanpcmcquen gotcha, That's what I am doing now. I have a separate plugin using simple variables to grab the ID and pull the rest of the data from Shopify with their API.  Looks like that is the right way to go as of now.

**Comment by ryanpcmcquen** [comment]
@bfjare, I'd recommend keeping product data out of Craft. We did that with our catalog and Craft's internal schema did not scale well. Long story short, you end up with millions of rows in your relations table and some tricky puzzles to solve ...

**Comment by bfjare** [comment]
I wanted to provide more information on this after a full day working on the project. I feel all too often we figure things out (kinda) and then leave them, which I have no judgment on, but wanted to share my experience for anyone fighting this. @ryanpcmcquen is absolutely right on not having Shopify's data within Craft for obvious reasons he explained.  This plugin is actually right on for what you need.  High-level back-end devs with great experience in plugin development will look at this and the Shopify API and this and say cool no big deal. Dev's looking at this with a front end specialty will probably not have the same experience. That being said, even using the simple framework of something like the Business Logic plugin ("I don't know how to set up a plugin, are you crazy!") could get something working at a pretty high level with a couple of simple variables, basic simple PHP, and an understanding of how twig can loop through generic arrays.  All in all, for a free plug-in I really appreciate everyone involved in it and it makes a client's ability to manage a store pretty easy.  I'm thinking of writing a case study for it in the future, although I don't see it happening in the next few weeks. If anyone is looking at this and is interested in how it can be done in a somewhat simple manner (with guidance) please let me know. Once, again thanks for all of your work everyone, I owe you a beer.
