### ISSUE TITLE
Array to string error (caused by Product name changing?)

### ISSUE THREAD

**Issue by j-greig** [nmaier95/craft-shopify-product-fetcher#22]
We're having a repeated problem where an entry can't be saved — perhaps because the previously selected Shopify product has a new name/title?

![image](https://user-images.githubusercontent.com/616194/86371608-fcb46680-bc78-11ea-88da-fc649c87ae37.png)

**Comment by nmaier95** [comment]
Quite a few variables beeing used on line 78 inside of ShopifyService.php. Do you have the chance to run it xdebug and step through it? Perhaps somewhere a false value is set.

I am also a bit confused this error is thrown 'on save'. If I remember correctly, in the flow of 'saving' this line is not executed. But maybe I'm wrong here...

**Comment by nmaier95** [comment]
closed due to inactivity.
