### ISSUE TITLE
Async option

### ISSUE THREAD

**Issue by knynkwl** [nmaier95/craft-shopify-product-fetcher#24]
Hey!

We are running into an issue where fetching the data for each product is taking a long time and the page's TTFB is really long. Is there an option for async fetching of data?

**Comment by nmaier95** [comment]
No, there is no async loading support by this plugin. 

What I can think off though, to help you improve your pageload is either pass product ids via data attributes (or json dump) into the templates and then load your data via Javascript asynchounously (might require some client-side rendering library or even custom logic). Or simply use the `cache`-tag for your data portions of the template -> [craft cache tag docs](https://craftcms.com/docs/3.x/dev/tags.html#cache)

**Comment by nmaier95** [comment]
Closed due to inactivity. Feel free to reopen if needed.
