### ISSUE TITLE
Crash on change to Craft Pro

### ISSUE THREAD

**Issue by thiagorossener** [nmaier95/craft-shopify-product-fetcher#3]
Hey @nmaier95, thank you for the great plugin! It's been working almost perfectly.

However, we got this bug and we are desperate looking for a solution, we really appreciate if you could help us out.

Basically, when we change from Craft Trial to Craft Pro, the plugin breaks. I'll show you some screenshots explaining this better.

**The plugin is installed.**

![image1](https://user-images.githubusercontent.com/1750826/49511499-7e13ff00-f872-11e8-86eb-1872919c0b2c.png)

**It's also set up.**

![image2](https://user-images.githubusercontent.com/1750826/49511537-9421bf80-f872-11e8-9a12-4dcb8cb0776e.png)

**I can see the Shopify product in the list, can select it and save it.**

![image3](https://user-images.githubusercontent.com/1750826/49511589-b1ef2480-f872-11e8-8c87-1d34485942a9.png)

**In the "Group view", it's everything ok.**

![image4](https://user-images.githubusercontent.com/1750826/49511603-bd425000-f872-11e8-8c29-df29b9a50bad.png)

**In the "All fields", it's showing an error.**

![image5](https://user-images.githubusercontent.com/1750826/49511617-c8957b80-f872-11e8-8f9e-6e76b98a5fa5.png)

**In the actual field, the same error.**

![image6](https://user-images.githubusercontent.com/1750826/49511632-d0edb680-f872-11e8-9269-e1c9324898b9.png)

**Finally, after changing to Pro, the product page doesn't work anymore. The product comes with a "false" value.**

![image7](https://user-images.githubusercontent.com/1750826/49511650-dcd97880-f872-11e8-97db-3865f1127607.png)

I've tried uninstall/install it, and disable/enable it, without success.

Do you have any idea what could possibly be wrong?

**Comment by nmaier95** [comment]
Hi @thiagorossener,

I haven't tested this this plugin with craft 3 pro tbh.
Did you install craft via composer? If so, have you tried dumping composer autoloads? This is done via the command-line in the root of your craft 3 project:

`composer dump-autoload --optimize`

If it still doesn't work please let me know, I'll then have to dig deeper into it and debug it by myself.

Greetings.

**Comment by thiagorossener** [comment]
Hey @nmaier95,

Thank you for the really quick response!

Just an update. We found out that there is something to do with the [Migrations Manager plugin](https://github.com/Firstborn/Craft-Migration-Manager).

When we disable this plugin, it works again.

In the plugin documentation, it says all the field types supported and how to implement the migration to custom fields:

> To handle export/import of custom field types your plugin/module should listen for the Export/Import events that are triggered from elements that utilize fields. Following is the list of elements that the Migration Manager has events for that allow you to modify the export/import data to support custom fields.

I believe that, for obvious reasons, Shopify Product field doesn't have it implemented.

It still doesn't make much sense why in Craft trial it works and in Craft Pro it doesn't.

I'll try to do what you said and let you know if there is any progress.

**Comment by Geestig** [comment]
Even after adding the above commit to the plugin it does not seem to fix the issue for my case. I can make the field, it gets shown but it doesn't save and doesn't show anything.

Without using the field I'm able to return some of my data but not everything.

**Comment by RobErskine** [comment]
@thiagorossener does this happen if you already have Craft Pro installed, vs going from Trial -> Pro?

I'm hopeful that I can leverage @nmaier95's awesome plugin but this is definitely a showstopper. Lemme know if I can help debug or if anything has happened on this since early April.

**Comment by nmaier95** [comment]
Hi @RobErskine , @thiagorossener ,

unfortunately I haven't had much time in the past to continue debugging this. Also I do not own a Craft-Pro licence for reproduction. @RobErskine do you have any troubles with this plugin on Craft-Pro as well?
Maybe the suggestion to add support for the Migration Manager might solve it already? I might have some time in the next few days to try and implement it.

Greetings.

**Comment by nmaier95** [comment]
closed due to inactivity.
