### ISSUE TITLE
Plugin won't enable on Craft 3.3.6

### ISSUE THREAD

**Issue by england9911** [nmaier95/craft-shopify-product-fetcher#6]
Have yet to write a plugin myself for Craft so not sure where to start debugging right now. Just flagging this as it's happened over a couple of different environments now but seems to have occurred after upgrading Craft to 3.3.6

Environment looks like this:

**Application Info**

PHP version 7.2.22
OS version  Linux 3.10.0-714.10.2.lve1.4.63.el7.x86_64
Database driver & version MySQL 5.5.5
Image driver & version  GD 7.2.22
Craft edition & version Craft Solo 3.3.6
Yii version 2.0.21
Twig version  2.11.3
Guzzle version  6.3.3
Imagine version 1.2.3-dev

**Plugins**

Architect 2.3.1
CP Clear Cache  1.0.4
CP Field Inspect  1.0.6
Instagram Feed  1.0.4
Logs  3.0.1
Mailchimp Subscribe 3.0.0
oEmbed  1.1.8
Outpost 1.1.1
Redactor  2.4.0
Seeder  3.0.1
SEO 3.6.2
Simple Sharing  1.0.5
Super Table 2.3.0
Typed link field  1.0.19

**Comment by england9911** [comment]
Update: Installed on a fresh vanilla craft 3.3.6 and got the error:

> Error: Class name must be a valid object or a string

**Comment by england9911** [comment]
I'm not familiar enough with Craft plugins or the inner workings of Composer to be able to the bottom of this today, but I narrowed it down to the createPlugin() method in the Plugins service during the install process.

To recreate, do a fresh install of Craft 3.3.6 and from the Plugin store try to install the plugin. 

The `return null` is being hit because '\shopify\Shopify' is not a subclass of craft\base\PluginInterface - e.g. it never gets loaded properly.

`
        // Make sure the class exists and it implements PluginInterface
        if (!is_subclass_of($class, PluginInterface::class)) {
            return null;
        }
`

I hope this helps a little @nmaier95 - we could really do with this plugin working! Happy to sponsor any work if required.

**Comment by nmaier95** [comment]
Hi @england9911 , thank you for your feedback. i'll have a look at this error in the near future.

**Comment by nmaier95** [comment]
Fix has been published with release [1.0.4](https://github.com/nmaier95/craft-shopify-product-fetcher/releases/tag/1.0.4).
I'll close this issue for now, if the error appears again, do not hesitate reopening this issue again or create a new one.

**Comment by england9911** [comment]
Thanks for moving so quickly on this. If you've got a donation link we'd be happy to drop something in there to show our appreciation.

**Comment by nmaier95** [comment]
Hi @england9911 if you feel like donating something, heres a link to a public amazon-wishlist of mine: https://www.amazon.de/hz/wishlist/ls/1AHM2XHEWM9QO?ref_=wl_share

Please do not feel like you really have to donate anything.
