### ISSUE TITLE
Not able to save Shopify Product field

### ISSUE THREAD

**Issue by england9911** [nmaier95/craft-shopify-product-fetcher#7]
I've tried this with changing a field type from Plain Text -> Shopify Product, and also adding a brand new Shopify Product field. We just get the 'Couldn't save field' error each time. 

This happens on a fresh install of Craft 3.3.6 and the latest version of the plugin (1.0.4). Also it seems to happen on Craft 3.3.8

There are 220 products being pulled in from Shopify, not sure if that may be causing a memory issue but I don't see anything in the logs.

**Comment by nmaier95** [comment]
Fix has been published with version [1.0.5](https://github.com/nmaier95/craft-shopify-product-fetcher/releases/tag/1.0.5)
